# Import libraries

In [ ]:
#Here we want to understand which features are strongly associated to survived = yes. eg. if 1st class, Male->Yes OR female->yes
#Install 'mlxtend' Library if not installed already
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.11/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.16.0)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from mlxtend) (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
import mlxtend

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
titanic = pd.read_csv("Titanic.csv")
titanic

     Class  Gender    Age Survived
0      3rd    Male  Child       No
1      3rd    Male  Child       No
2      3rd    Male  Child       No
3      3rd    Male  Child       No
4      3rd    Male  Child       No
...    ...     ...    ...      ...
2196  Crew  Female  Adult      Yes
2197  Crew  Female  Adult      Yes
2198  Crew  Female  Adult      Yes
2199  Crew  Female  Adult      Yes
2200  Crew  Female  Adult      Yes

[2201 rows x 4 columns]

In [ ]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [ ]:
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [ ]:
titanic['Age'].value_counts()

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [ ]:
titanic['Survived'].value_counts()

Survived
No     1490
Yes     711
Name: count, dtype: int64

# Pre-Processing
As the data is not in transaction formation
# We are using **transaction Encoder**

In [ ]:
array = titanic.values

In [ ]:
encoder = TransactionEncoder()
onehot = encoder.fit_transform(array)
onehot_df = pd.DataFrame(onehot, columns=encoder.columns_)

In [ ]:
onehot_df

        1st    2nd    3rd  Adult  Child   Crew  Female   Male     No    Yes
0     False  False   True  False   True  False   False   True   True  False
1     False  False   True  False   True  False   False   True   True  False
2     False  False   True  False   True  False   False   True   True  False
3     False  False   True  False   True  False   False   True   True  False
4     False  False   True  False   True  False   False   True   True  False
...     ...    ...    ...    ...    ...    ...     ...    ...    ...    ...
2196  False  False  False   True  False   True    True  False  False   True
2197  False  False  False   True  False   True    True  False  False   True
2198  False  False  False   True  False   True    True  False  False   True
2199  False  False  False   True  False   True    True  False  False   True
2200  False  False  False   True  False   True    True  False  False   True

[2201 rows x 10 columns]

# **OR Use get_dummies() method**

In [ ]:
df=pd.get_dummies(titanic)
df

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,False,False,True,False,False,True,False,True,True,False
1,False,False,True,False,False,True,False,True,True,False
2,False,False,True,False,False,True,False,True,True,False
3,False,False,True,False,False,True,False,True,True,False
4,False,False,True,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...
2196,False,False,False,True,True,False,True,False,False,True
2197,False,False,False,True,True,False,True,False,False,True
2198,False,False,False,True,True,False,True,False,False,True
2199,False,False,False,True,True,False,True,False,False,True
2200,False,False,False,True,True,False,True,False,False,True

# Apriori Algorithm

Practical steps for choosing min_support
Start with a moderate value like 0.1 (10%)

Observe number of frequent itemsets:

Too many? âž” Increase min_support

Too few or none? âž” Decrease min_support

Adjust based on business logic:

If a "rare event" is still valuable (e.g., buying a luxury item), use lower support.

If you want only very frequent combinations (e.g., bread + milk), use higher support.

Thumb Rules for min_support:
Dataset size:	Suggested min_support
10k+ transactions:	0.05â€“0.2,
100â€“10k transactions:	0.01â€“0.1,
<100 transactions:	0.005â€“0.05

In [ ]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)#df-dataframe, min_support default=0.5
# min_support=0.1: keep only those itemsets appearing in at least 10% of transactions.
# min_support is a float between 0 and 1 for minumum support of the itemsets returned.
# The support is computed as the fraction transactions_where_item(s)_occur / total_transactions.
frequent_itemsets # output is frequent itemsets: 1-item itemsets, 2-item itemsets etc. with min support criteria

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Age_Adult, Class_2nd)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Class_3rd, Survived_No)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Class_Crew, Survived_No)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Gender_Male, Survived_Yes)
22  0.653339                           (Age_Adult, Survived_No)
23  0.297138                          (Age_Adult, Survived_Yes)
24  0.209905                (Class_3rd, Age_Adult, Gender_Male)
25  0.191731              (Class_3rd, Survived_No, Gender_Male)
26  0.216265                (Class_3rd, Age_Adult, Survived_No)
27  0.391640               (Class_Crew, Age_Adult, Gender_Male)
28  0.304407             (Class_Crew, Survived_No, Gender_Male)
29  0.305770               (Class_Crew, Age_Adult, Survived_No)
30  0.143571           (Age_Adult, Gender_Female, Survived_Yes)
31  0.603816              (Age_Adult, Survived_No, Gender_Male)
32  0.153567             (Age_Adult, Gender_Male, Survived_Yes)
33  0.175829   (Class_3rd, Age_Adult, Survived_No, Gender_Male)
34  0.304407  (Class_Crew, Age_Adult, Survived_No, Gender_Male)

In [ ]:
rules = association_rules(frequent_itemsets, metric="lift",num_itemsets=2201, min_threshold=1.2) # min_threshold is Confidence 1.2
rules # http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
rules.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
14,"(Age_Adult, Gender_Female)",(Survived_Yes),0.193094,0.323035,0.143571,0.743529,2.301699,1.0,0.081195,2.639542,0.700873,0.385366,0.621146,0.593987
17,(Survived_Yes),"(Age_Adult, Gender_Female)",0.323035,0.193094,0.143571,0.444444,2.301699,1.0,0.081195,1.452431,0.835403,0.385366,0.311499,0.593987
3,(Survived_Yes),(Gender_Female),0.323035,0.213539,0.156293,0.483826,2.265745,1.0,0.087312,1.523634,0.825219,0.410992,0.343674,0.607870
2,(Gender_Female),(Survived_Yes),0.213539,0.323035,0.156293,0.731915,2.265745,1.0,0.087312,2.525187,0.710327,0.410992,0.603990,0.607870
15,"(Age_Adult, Survived_Yes)",(Gender_Female),0.297138,0.213539,0.143571,0.483180,2.262724,1.0,0.080121,1.521732,0.793974,0.391089,0.342854,0.577760
16,(Gender_Female),"(Age_Adult, Survived_Yes)",0.213539,0.297138,0.143571,0.672340,2.262724,1.0,0.080121,2.145099,0.709577,0.391089,0.533821,0.577760
23,"(Class_Crew, Survived_No)","(Age_Adult, Gender_Male)",0.305770,0.757383,0.304407,0.995542,1.314450,1.0,0.072822,54.427079,0.344592,0.401198,0.981627,0.698731
24,"(Age_Adult, Gender_Male)","(Class_Crew, Survived_No)",0.757383,0.305770,0.304407,0.401920,1.314450,1.0,0.072822,1.160764,0.986022,0.401198,0.138498,0.698731
8,(Class_Crew),"(Age_Adult, Gender_Male)",0.402090,0.757383,0.391640,0.974011,1.286022,1.0,0.087104,9.335480,0.371976,0.510059,0.892882,0.745554
7,"(Age_Adult, Gender_Male)",(Class_Crew),0.757383,0.402090,0.391640,0.517097,1.286022,1.0,0.087104,1.238157,0.916706,0.510059,0.192348,0.745554
10,"(Class_Crew, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
20,"(Class_Crew, Age_Adult, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
27,(Gender_Male),"(Class_Crew, Age_Adult, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
13,(Gender_Male),"(Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
21,"(Age_Adult, Survived_No, Gender_Male)",(Class_Crew),0.603816,0.402090,0.304407,0.504138,1.253795,1.0,0.061619,1.205800,0.510929,0.433938,0.170675,0.630600
26,(Class_Crew),"(Age_Adult, Survived_No, Gender_Male)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600
0,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
6,"(Class_Crew, Age_Adult)",(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
1,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
9,(Gender_Male),"(Class_Crew, Age_Adult)",0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995

In [ ]:
rules[rules.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
1,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
2,(Gender_Female),(Survived_Yes),0.213539,0.323035,0.156293,0.731915,2.265745,1.0,0.087312,2.525187,0.710327,0.410992,0.603990,0.607870
3,(Survived_Yes),(Gender_Female),0.323035,0.213539,0.156293,0.483826,2.265745,1.0,0.087312,1.523634,0.825219,0.410992,0.343674,0.607870
4,"(Class_3rd, Gender_Male)",(Survived_No),0.231713,0.676965,0.191731,0.827451,1.222295,1.0,0.034870,1.872135,0.236717,0.267427,0.465850,0.555336
5,(Survived_No),"(Class_3rd, Gender_Male)",0.676965,0.231713,0.191731,0.283221,1.222295,1.0,0.034870,1.071861,0.562995,0.267427,0.067043,0.555336
6,"(Class_Crew, Age_Adult)",(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
7,"(Age_Adult, Gender_Male)",(Class_Crew),0.757383,0.402090,0.391640,0.517097,1.286022,1.0,0.087104,1.238157,0.916706,0.510059,0.192348,0.745554
8,(Class_Crew),"(Age_Adult, Gender_Male)",0.402090,0.757383,0.391640,0.974011,1.286022,1.0,0.087104,9.335480,0.371976,0.510059,0.892882,0.745554
9,(Gender_Male),"(Class_Crew, Age_Adult)",0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
10,"(Class_Crew, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
11,"(Survived_No, Gender_Male)",(Class_Crew),0.619718,0.402090,0.304407,0.491202,1.221623,1.0,0.055225,1.175143,0.477059,0.424319,0.149040,0.624132
12,(Class_Crew),"(Survived_No, Gender_Male)",0.402090,0.619718,0.304407,0.757062,1.221623,1.0,0.055225,1.565346,0.303418,0.424319,0.361163,0.624132
13,(Gender_Male),"(Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
14,"(Age_Adult, Gender_Female)",(Survived_Yes),0.193094,0.323035,0.143571,0.743529,2.301699,1.0,0.081195,2.639542,0.700873,0.385366,0.621146,0.593987
15,"(Age_Adult, Survived_Yes)",(Gender_Female),0.297138,0.213539,0.143571,0.483180,2.262724,1.0,0.080121,1.521732,0.793974,0.391089,0.342854,0.577760
16,(Gender_Female),"(Age_Adult, Survived_Yes)",0.213539,0.297138,0.143571,0.672340,2.262724,1.0,0.080121,2.145099,0.709577,0.391089,0.533821,0.577760
17,(Survived_Yes),"(Age_Adult, Gender_Female)",0.323035,0.193094,0.143571,0.444444,2.301699,1.0,0.081195,1.452431,0.835403,0.385366,0.311499,0.593987
18,"(Class_3rd, Age_Adult, Gender_Male)",(Survived_No),0.209905,0.676965,0.175829,0.837662,1.237379,1.0,0.033731,1.989896,0.242806,0.247284,0.497461,0.548697
19,(Survived_No),"(Class_3rd, Age_Adult, Gender_Male)",0.676965,0.209905,0.175829,0.259732,1.237379,1.0,0.033731,1.067309,0.593868,0.247284,0.063064,0.548697
20,"(Class_Crew, Age_Adult, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
21,"(Age_Adult, Survived_No, Gender_Male)",(Class_Crew),0.603816,0.402090,0.304407,0.504138,1.253795,1.0,0.061619,1.205800,0.510929,0.433938,0.170675,0.630600
22,"(Class_Crew, Age_Adult)","(Survived_No, Gender_Male)",0.402090,0.619718,0.304407,0.757062,1.221623,1.0,0.055225,1.565346,0.303418,0.424319,0.361163,0.624132
23,"(Class_Crew, Survived_No)","(Age_Adult, Gender_Male)",0.305770,0.757383,0.304407,0.995542,1.314450,1.0,0.072822,54.427079,0.344592,0.401198,0.981627,0.698731
24,"(Age_Adult, Gender_Male)","(Class_Crew, Survived_No)",0.757383,0.305770,0.304407,0.401920,1.314450,1.0,0.072822,1.160764,0.986022,0.401198,0.138498,0.698731
25,"(Survived_No, Gender_Male)","(Class_Crew, Age_Adult)",0.619718,0.402090,0.304407,0.491202,1.221623,1.0,0.055225,1.175143,0.477059,0.424319,0.149040,0.624132
26,(Class_Crew),"(Age_Adult, Survived_No, Gender_Male)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600
27,(Gender_Male),"(Class_Crew, Age_Adult, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301

# Another Example with Retail_Dataset

In [ ]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
df = pd.read_csv('/content/retail_dataset.csv')
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

        0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

In [ ]:
df.shape

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(315, 7)

In [ ]:
# Find unique values of column index 0.
items = (df['0'].unique())
items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['Bread', 'Cheese', 'Meat', 'Eggs', 'Wine', 'Bagel', 'Pencil',
       'Diaper', 'Milk'], dtype=object)

In [ ]:
items = (df['1'].unique())
items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['Wine', 'Cheese', 'Meat', 'Pencil', 'Bread', 'Diaper', 'Eggs', nan,
       'Bagel', 'Milk'], dtype=object)

In [ ]:
# One-hot encoding
encoded_vals = []
for index, row in df.iterrows(): # iterrows() returns index and content for each row
    labels = {}
    uncommons = list(set(items) - set(row))#total 9 items (Bagel,Milk,...,pencil) - items present in row = Bagel, Milk (for 1st row these 2 items are not present)
    commons = list(set(items).intersection(row))# common items
    for uc in uncommons:
        labels[uc] = 0 # assign 0 to uncommon items
    for com in commons:
        labels[com] = 1# assign 1 to common items
    encoded_vals.append(labels)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
encoded_vals

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[{'Milk': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Eggs': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  'Wine': 1,
  nan: 1,
  'Pencil': 1},
 {'Meat': 0,
  'Cheese': 0,
  nan: 0,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Meat': 0,
  'Bagel': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1},
 {'Meat': 0,
  'Cheese': 0,
  'Wine': 0,
  'Eggs': 0,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Meat': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bread': 0,
  'Milk': 0,
  nan: 0,
  'Cheese': 1,
  'Meat': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  nan: 0,
  'Pencil': 0,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  nan: 1,
  'Meat': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  nan: 1},
 {'Cheese': 0,
  'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  nan: 1,
  'Bread': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1},
 {'Wine': 0,
  'Milk': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Bread': 1,
  'Meat': 1},
 {'Diaper': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Bread': 0,
  'Wine': 0,
  'Milk': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Bread': 0,
  'Cheese': 0,
  'Milk': 0,
  'Bagel': 0,
  nan: 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Meat': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Pencil': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Eggs': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  nan: 1,
  'Bagel': 1},
 {'Wine': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1,
  'Meat': 1},
 {'Meat': 0,
  'Milk': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  'Cheese': 1,
  nan: 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Milk': 0,
  'Pencil': 0,
  'Eggs': 0,
  nan: 1,
  'Bagel': 1,
  'Meat': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Meat': 0,
  'Eggs': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Eggs': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  nan: 1},
 {'Meat': 0,
  'Diaper': 0,
  nan: 0,
  'Cheese': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Eggs': 1,
  nan: 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  'Wine': 1,
  nan: 1,
  'Meat': 1},
 {'Meat': 0,
  nan: 0,
  'Pencil': 0,
  'Cheese': 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Wine': 1,
  nan: 1,
  'Eggs': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Wine': 1,
  nan: 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1},
 {'Meat': 0,
  'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  nan: 1,
  'Bagel': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Milk': 0,
  'Eggs': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Meat': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Bread': 0,
  'Meat': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1,
  'Milk': 1},
 {nan: 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1,
  'Eggs': 1},
 {'Bread': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Milk': 0,
  nan: 0,
  'Eggs': 0,
  'Cheese': 1,
  'Bagel': 1,
  'Meat': 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Bread': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Eggs': 0,
  'Bagel': 0,
  nan: 1,
  'Meat': 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bread': 0,
  'Meat': 0,
  'Milk': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Meat': 0,
  'Wine': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Meat': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  'Milk': 1,
  nan: 1,
  'Pencil': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  'Bagel': 1,
  nan: 1,
  'Eggs': 1},
 {'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Meat': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  nan: 1,
  'Bagel': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  nan: 1,
  'Eggs': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Bagel': 0,
  'Wine': 0,
  'Bread': 0,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Meat': 1,
  'Milk': 1},
 {'Wine': 0,
  'Milk': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Meat': 1,
  'Bagel': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Meat': 0,
  'Milk': 0,
  nan: 0,
  'Cheese': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  nan: 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  nan: 1,
  'Pencil': 1},
 {'Meat': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  'Wine': 1,
  nan: 1,
  'Milk': 1},
 {'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  'Wine': 1,
  nan: 1,
  'Pencil': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1},
 {'Cheese': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  nan: 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Bread': 0,
  'Milk': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1},
 {'Diaper': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Meat': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Diaper': 0,
  'Eggs': 0,
  'Milk': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1},
 {'Diaper': 0,
  nan: 0,
  'Eggs': 0,
  'Cheese': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bread': 0,
  'Meat': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Wine': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bread': 0,
  'Milk': 0,
  nan: 0,
  'Cheese': 1,
  'Bagel': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Bread': 0,
  nan: 0,
  'Pencil': 0,
  'Cheese': 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  nan: 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Pencil': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Meat': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Eggs': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Wine': 1,
  'Meat': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  'Wine': 1,
  nan: 1},
 {'Meat': 0,
  'Diaper': 0,
  'Bagel': 0,
  'Cheese': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Bread': 0,
  'Wine': 0,
  'Diaper': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Bread': 0,
  'Milk': 0,
  nan: 1,
  'Meat': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Meat': 1,
  'Diaper': 1,
  nan: 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Meat': 0,
  'Diaper': 0,
  nan: 1,
  'Pencil': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Diaper': 0,
  'Cheese': 0,
  nan: 0,
  'Bagel': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {nan: 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  'Bagel': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Bread': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Wine': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1},
 {'Meat': 0,
  'Wine': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Bread': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Meat': 1,
  nan: 1,
  'Milk': 1,
  'Pencil': 1},
 {'Milk': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  'Cheese': 1,
  nan: 1},
 {'Diaper': 0,
  'Cheese': 0,
  'Milk': 0,
  'Pencil': 0,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1},
 {'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1},
 {'Bread': 0,
  'Cheese': 0,
  'Milk': 0,
  'Eggs': 0,
  nan: 1,
  'Meat': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  nan: 1,
  'Milk': 1,
  'Pencil': 1},
 {'Bread': 0,
  'Cheese': 0,
  'Milk': 0,
  'Meat': 0,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Diaper': 1},
 {'Diaper': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Meat': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  'Bread': 1,
  nan: 1,
  'Pencil': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Pencil': 0,
  'Bread': 0,
  'Diaper': 0,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Milk': 1},
 {'Bread': 0,
  'Diaper': 0,
  nan: 0,
  'Cheese': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Meat': 1,
  'Milk': 1},
 {'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  nan: 1,
  'Pencil': 1,
  'Bread': 1,
  'Diaper': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Bread': 1,
  nan: 1,
  'Milk': 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  nan: 1},
 {'Cheese': 0,
  'Milk': 0,
  'Pencil': 0,
  'Eggs': 0,
  nan: 1,
  'Bagel': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Bagel': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Bread': 0,
  'Milk': 0,
  'Diaper': 1,
  'Wine': 1,
  nan: 1},
 {'Bread': 0,
  'Wine': 0,
  'Milk': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Meat': 1,
  'Diaper': 1},
 {'Cheese': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Bread': 1},
 {'Diaper': 0,
  nan: 0,
  'Bagel': 0,
  'Cheese': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  'Meat': 1,
  nan: 1,
  'Pencil': 1,
  'Eggs': 1},
 {'Cheese': 0,
  'Meat': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  'Milk': 0,
  nan: 1,
  'Pencil': 1,
  'Bagel': 1},
 {'Diaper': 0,
  'Wine': 0,
  'Milk': 0,
  'Cheese': 1,
  nan: 1,
  'Meat': 1,
  'Bagel': 1,
  'Pencil': 1,
  'Eggs': 1,
  'Bread': 1},
 {'Bagel': 0,
  'Pencil': 0,
  'Wine': 0,
  'Meat': 0,
  'Diaper': 0,
  'Cheese': 1,
  nan: 1,
  'Eggs': 1,
  'Bread': 1,
  'Milk': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Meat': 0,
  'Pencil': 0,
  'Eggs': 0,
  'Wine': 0,
  'Bread': 0,
  'Diaper': 0,
  nan: 1,
  'Milk': 1},
 {'Diaper': 0,
  'Wine': 0,
  'Milk': 0,
  'Eggs': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Pencil': 1,
  'Bread': 1,
  'Meat': 1},
 {'Cheese': 0,
  'Bagel': 0,
  'Pencil': 0,
  'Meat': 0,
  'Milk': 0,
  nan: 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Diaper': 1},
 {'Diaper': 0,
  'Milk': 0,
  'Pencil': 0,
  'Cheese': 1,
  nan: 1,
  'Bagel': 1,
  'Eggs': 1,
  'Wine': 1,
  'Bread': 1,
  'Meat': 1},

In [ ]:
ohe_df = pd.DataFrame(encoded_vals)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
ohe_df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     Milk  NaN  Bagel  Cheese  Meat  Pencil  Eggs  Wine  Bread  Diaper
0       0    0      0       1     1       1     1     1      1       1
1       1    0      0       1     1       1     0     1      1       1
2       1    1      0       1     1       0     1     1      0       0
3       1    1      0       1     1       0     1     1      0       0
4       0    1      0       0     1       1     0     1      0       0
..    ...  ...    ...     ...   ...     ...   ...   ...    ...     ...
310     0    1      0       1     0       0     1     0      1       0
311     1    1      0       0     1       1     0     0      0       0
312     0    0      0       1     1       1     1     1      1       1
313     0    1      0       1     1       0     0     0      0       0
314     0    1      1       0     1       0     1     1      1       0

[315 rows x 10 columns]

In [ ]:
freq_items = apriori(ohe_df, min_support = 0.2, use_colnames = True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [ ]:
freq_items

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support              itemsets
0   0.501587                (Milk)
1   0.869841                 (nan)
2   0.425397               (Bagel)
3   0.501587              (Cheese)
4   0.476190                (Meat)
5   0.361905              (Pencil)
6   0.438095                (Eggs)
7   0.438095                (Wine)
8   0.504762               (Bread)
9   0.406349              (Diaper)
10  0.409524           (nan, Milk)
11  0.225397         (Milk, Bagel)
12  0.304762        (Cheese, Milk)
13  0.244444          (Meat, Milk)
14  0.244444          (Milk, Eggs)
15  0.219048          (Wine, Milk)
16  0.279365         (Bread, Milk)
17  0.336508          (nan, Bagel)
18  0.393651         (Cheese, nan)
19  0.368254           (Meat, nan)
20  0.266667         (nan, Pencil)
21  0.336508           (nan, Eggs)
22  0.317460           (Wine, nan)
23  0.396825          (Bread, nan)
24  0.317460         (Diaper, nan)
25  0.279365        (Bread, Bagel)
26  0.323810        (Meat, Cheese)
27  0.200000      (Cheese, Pencil)
28  0.298413        (Cheese, Eggs)
29  0.269841        (Cheese, Wine)
30  0.238095       (Bread, Cheese)
31  0.200000      (Diaper, Cheese)
32  0.266667          (Meat, Eggs)
33  0.250794          (Meat, Wine)
34  0.206349         (Bread, Meat)
35  0.200000        (Wine, Pencil)
36  0.200000       (Bread, Pencil)
37  0.241270          (Wine, Eggs)
38  0.244444         (Bread, Wine)
39  0.234921        (Diaper, Wine)
40  0.231746       (Bread, Diaper)
41  0.234921   (Cheese, nan, Milk)
42  0.203175  (Meat, Cheese, Milk)
43  0.212698   (Bread, nan, Bagel)
44  0.234921   (Meat, Cheese, nan)
45  0.219048   (Cheese, nan, Eggs)
46  0.215873  (Meat, Cheese, Eggs)

In [ ]:
asso_rules=association_rules(freq_items, metric = "confidence", num_itemsets = 315, min_threshold = 0.6) # can use metric as lift

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
asso_rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Milk),(nan),0.501587,0.869841,0.409524,0.816456,0.938626,1.0,-0.026778,0.709141,-0.115976,0.425743,-0.410157,0.643629
1,(Cheese),(Milk),0.501587,0.501587,0.304762,0.607595,1.211344,1.0,0.053172,1.270148,0.350053,0.436364,0.212690,0.607595
2,(Milk),(Cheese),0.501587,0.501587,0.304762,0.607595,1.211344,1.0,0.053172,1.270148,0.350053,0.436364,0.212690,0.607595
3,(Bagel),(nan),0.425397,0.869841,0.336508,0.791045,0.909413,1.0,-0.033520,0.622902,-0.147743,0.350993,-0.605388,0.588953
4,(Cheese),(nan),0.501587,0.869841,0.393651,0.784810,0.902245,1.0,-0.042651,0.604855,-0.178565,0.402597,-0.653288,0.618682
5,(Meat),(nan),0.476190,0.869841,0.368254,0.773333,0.889051,1.0,-0.045956,0.574230,-0.192405,0.376623,-0.741463,0.598345
6,(Pencil),(nan),0.361905,0.869841,0.266667,0.736842,0.847100,1.0,-0.048133,0.494603,-0.220499,0.276316,-1.021823,0.521706
7,(Eggs),(nan),0.438095,0.869841,0.336508,0.768116,0.883053,1.0,-0.044565,0.561310,-0.190735,0.346405,-0.781548,0.577489
8,(Wine),(nan),0.438095,0.869841,0.317460,0.724638,0.833069,1.0,-0.063613,0.472682,-0.262869,0.320513,-1.115589,0.544801
9,(Bread),(nan),0.504762,0.869841,0.396825,0.786164,0.903801,1.0,-0.042237,0.608683,-0.176903,0.405844,-0.642890,0.621184
10,(Diaper),(nan),0.406349,0.869841,0.317460,0.781250,0.898152,1.0,-0.035999,0.595011,-0.160381,0.331126,-0.680640,0.573107
11,(Bagel),(Bread),0.425397,0.504762,0.279365,0.656716,1.301042,1.0,0.064641,1.442650,0.402687,0.429268,0.306831,0.605088
12,(Meat),(Cheese),0.476190,0.501587,0.323810,0.680000,1.355696,1.0,0.084958,1.557540,0.500891,0.495146,0.357962,0.662785
13,(Cheese),(Meat),0.501587,0.476190,0.323810,0.645570,1.355696,1.0,0.084958,1.477891,0.526414,0.495146,0.323360,0.662785
14,(Eggs),(Cheese),0.438095,0.501587,0.298413,0.681159,1.358008,1.0,0.078670,1.563203,0.469167,0.465347,0.360288,0.638048
15,(Wine),(Cheese),0.438095,0.501587,0.269841,0.615942,1.227986,1.0,0.050098,1.297754,0.330409,0.402844,0.229438,0.576958
16,(Eggs),(Meat),0.438095,0.476190,0.266667,0.608696,1.278261,1.0,0.058050,1.338624,0.387409,0.411765,0.252964,0.584348
17,"(Cheese, Milk)",(nan),0.304762,0.869841,0.234921,0.770833,0.886177,1.0,-0.030174,0.567965,-0.155938,0.250000,-0.760671,0.520453
18,"(Meat, Cheese)",(Milk),0.323810,0.501587,0.203175,0.627451,1.250931,1.0,0.040756,1.337845,0.296655,0.326531,0.252529,0.516257
19,"(Meat, Milk)",(Cheese),0.244444,0.501587,0.203175,0.831169,1.657077,1.0,0.080564,2.952137,0.524816,0.374269,0.661262,0.618116
20,"(Cheese, Milk)",(Meat),0.304762,0.476190,0.203175,0.666667,1.400000,1.0,0.058050,1.571429,0.410959,0.351648,0.363636,0.546667
21,"(Bread, Bagel)",(nan),0.279365,0.869841,0.212698,0.761364,0.875290,1.0,-0.030305,0.545427,-0.165075,0.227119,-0.833426,0.502945
22,"(nan, Bagel)",(Bread),0.336508,0.504762,0.212698,0.632075,1.252225,1.0,0.042842,1.346032,0.303578,0.338384,0.257075,0.526730
23,"(Meat, Cheese)",(nan),0.323810,0.869841,0.234921,0.725490,0.834049,1.0,-0.046742,0.474150,-0.227353,0.245033,-1.109039,0.497782
24,"(Meat, nan)",(Cheese),0.368254,0.501587,0.234921,0.637931,1.271825,1.0,0.050209,1.376568,0.338313,0.370000,0.273556,0.553143
25,"(Cheese, Eggs)",(nan),0.298413,0.869841,0.219048,0.734043,0.843881,1.0,-0.040524,0.489397,-0.208666,0.230769,-1.043332,0.492934
26,"(nan, Eggs)",(Cheese),0.336508,0.501587,0.219048,0.650943,1.297767,1.0,0.050260,1.427885,0.345815,0.353846,0.299664,0.543826
27,"(Meat, Cheese)",(Eggs),0.323810,0.438095,0.215873,0.666667,1.521739,1.0,0.074014,1.685714,0.507042,0.395349,0.406780,0.579710
28,"(Meat, Eggs)",(Cheese),0.266667,0.501587,0.215873,0.809524,1.613924,1.0,0.082116,2.616667,0.518717,0.390805,0.617834,0.619952
29,"(Cheese, Eggs)",(Meat),0.298413,0.476190,0.215873,0.723404,1.519149,1.0,0.073772,1.893773,0.487091,0.386364,0.471954,0.588369

In [ ]:
asso_rules.sort_values('confidence',ascending = False) # can sort as lift value

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
19,"(Meat, Milk)",(Cheese),0.244444,0.501587,0.203175,0.831169,1.657077,1.0,0.080564,2.952137,0.524816,0.374269,0.661262,0.618116
0,(Milk),(nan),0.501587,0.869841,0.409524,0.816456,0.938626,1.0,-0.026778,0.709141,-0.115976,0.425743,-0.410157,0.643629
28,"(Meat, Eggs)",(Cheese),0.266667,0.501587,0.215873,0.809524,1.613924,1.0,0.082116,2.616667,0.518717,0.390805,0.617834,0.619952
3,(Bagel),(nan),0.425397,0.869841,0.336508,0.791045,0.909413,1.0,-0.033520,0.622902,-0.147743,0.350993,-0.605388,0.588953
9,(Bread),(nan),0.504762,0.869841,0.396825,0.786164,0.903801,1.0,-0.042237,0.608683,-0.176903,0.405844,-0.642890,0.621184
4,(Cheese),(nan),0.501587,0.869841,0.393651,0.784810,0.902245,1.0,-0.042651,0.604855,-0.178565,0.402597,-0.653288,0.618682
10,(Diaper),(nan),0.406349,0.869841,0.317460,0.781250,0.898152,1.0,-0.035999,0.595011,-0.160381,0.331126,-0.680640,0.573107
5,(Meat),(nan),0.476190,0.869841,0.368254,0.773333,0.889051,1.0,-0.045956,0.574230,-0.192405,0.376623,-0.741463,0.598345
17,"(Cheese, Milk)",(nan),0.304762,0.869841,0.234921,0.770833,0.886177,1.0,-0.030174,0.567965,-0.155938,0.250000,-0.760671,0.520453
7,(Eggs),(nan),0.438095,0.869841,0.336508,0.768116,0.883053,1.0,-0.044565,0.561310,-0.190735,0.346405,-0.781548,0.577489
21,"(Bread, Bagel)",(nan),0.279365,0.869841,0.212698,0.761364,0.875290,1.0,-0.030305,0.545427,-0.165075,0.227119,-0.833426,0.502945
6,(Pencil),(nan),0.361905,0.869841,0.266667,0.736842,0.847100,1.0,-0.048133,0.494603,-0.220499,0.276316,-1.021823,0.521706
25,"(Cheese, Eggs)",(nan),0.298413,0.869841,0.219048,0.734043,0.843881,1.0,-0.040524,0.489397,-0.208666,0.230769,-1.043332,0.492934
23,"(Meat, Cheese)",(nan),0.323810,0.869841,0.234921,0.725490,0.834049,1.0,-0.046742,0.474150,-0.227353,0.245033,-1.109039,0.497782
8,(Wine),(nan),0.438095,0.869841,0.317460,0.724638,0.833069,1.0,-0.063613,0.472682,-0.262869,0.320513,-1.115589,0.544801
29,"(Cheese, Eggs)",(Meat),0.298413,0.476190,0.215873,0.723404,1.519149,1.0,0.073772,1.893773,0.487091,0.386364,0.471954,0.588369
14,(Eggs),(Cheese),0.438095,0.501587,0.298413,0.681159,1.358008,1.0,0.078670,1.563203,0.469167,0.465347,0.360288,0.638048
12,(Meat),(Cheese),0.476190,0.501587,0.323810,0.680000,1.355696,1.0,0.084958,1.557540,0.500891,0.495146,0.357962,0.662785
20,"(Cheese, Milk)",(Meat),0.304762,0.476190,0.203175,0.666667,1.400000,1.0,0.058050,1.571429,0.410959,0.351648,0.363636,0.546667
27,"(Meat, Cheese)",(Eggs),0.323810,0.438095,0.215873,0.666667,1.521739,1.0,0.074014,1.685714,0.507042,0.395349,0.406780,0.579710
11,(Bagel),(Bread),0.425397,0.504762,0.279365,0.656716,1.301042,1.0,0.064641,1.442650,0.402687,0.429268,0.306831,0.605088
26,"(nan, Eggs)",(Cheese),0.336508,0.501587,0.219048,0.650943,1.297767,1.0,0.050260,1.427885,0.345815,0.353846,0.299664,0.543826
13,(Cheese),(Meat),0.501587,0.476190,0.323810,0.645570,1.355696,1.0,0.084958,1.477891,0.526414,0.495146,0.323360,0.662785
24,"(Meat, nan)",(Cheese),0.368254,0.501587,0.234921,0.637931,1.271825,1.0,0.050209,1.376568,0.338313,0.370000,0.273556,0.553143
22,"(nan, Bagel)",(Bread),0.336508,0.504762,0.212698,0.632075,1.252225,1.0,0.042842,1.346032,0.303578,0.338384,0.257075,0.526730
18,"(Meat, Cheese)",(Milk),0.323810,0.501587,0.203175,0.627451,1.250931,1.0,0.040756,1.337845,0.296655,0.326531,0.252529,0.516257
15,(Wine),(Cheese),0.438095,0.501587,0.269841,0.615942,1.227986,1.0,0.050098,1.297754,0.330409,0.402844,0.229438,0.576958
16,(Eggs),(Meat),0.438095,0.476190,0.266667,0.608696,1.278261,1.0,0.058050,1.338624,0.387409,0.411765,0.252964,0.584348
1,(Cheese),(Milk),0.501587,0.501587,0.304762,0.607595,1.211344,1.0,0.053172,1.270148,0.350053,0.436364,0.212690,0.607595
2,(Milk),(Cheese),0.501587,0.501587,0.304762,0.607595,1.211344,1.0,0.053172,1.270148,0.350053,0.436364,0.212690,0.607595